_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entityqueue: 0
  entityqueue_smartqueue: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_tabs: 0
  layout_builder: 0
  layout_builder_expose_all_field_blocks: 0
  layout_discovery: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quicktabs: 0
  quicktabs_accordion: 0
  quicktabs_jqueryui: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  shortcut: 0
  smtp: 0
  standard: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tooltip: 0
  tooltip_example: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_node: 0
  webform_templates: 0
  webform_ui: 0
  pathauto: 1
  webform_bootstrap: 1
  views: 10
theme:
  olivero: 0
  claro: 0
profile: standard
