_core:
  default_config_hash: K_DFQdghCE0fDsOmUJREQNNRHQS2F95ocKs2xVVsWQA
smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: swarnav.das@innoraft.com
smtp_password: 'tfvg zdmm anhh lgmh'
smtp_from: swarnav.das@innoraft.com
smtp_fromname: MovieMessage
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: itsswarnav007@gmail.com
smtp_reroute_address: ''
smtp_debugging: true
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: true
