_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: f222a991-ad28-4867-a0ed-c44465e37865
name: 'Movie portal'
mail: swarnav.das@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/13
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
